# Subscription

Subscribe Spec

## Subscription Collection [/subscriptions]

### Get subscriptions [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (Subscription)
        + (Subscription)
            + id: "2853553"
            + ServiceType: Reddit

### Post Subscription [POST]

+ Attributes (Subscription)
+ Request (application/json)
    + Header
        client_id: "356278"
    + Attributes (Subscription)

+ Response 201

## WidgetConfig [/widgetsConfig{?subscriptionsId}]

+ Parameters
    + subscriptionsId: (number, required)

### Get widgets config [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (OW_WEATHER_CONF)
        + (OW_WEATHER_CONF)
            + city: "Bordeaux"
        + (YT_NB_FOLLOWERS_CONF)

### Post widget config [POST]

+ Attributes (WidgetConfig)
+ Request (application/json)
    + Header
        client_id: "356278"
    + Attributes (YT_NB_LIKE_CONF)

+ Response 201

# Data Structures

## ServiceName (enum[String])
    + "Youtube"
    + "Reddit"
    + "Hackernews"
    + "twitter"

## WidgetType (enum[String])
    + "YT_NB_FOLLOWERS"
    + "YT_NB_LIKE"
    + "OW_WEATHER"
    + "HN_NB_LATEST_POST"
    + "REDDIT_LATEST_SUBREDIT_POST_NAME"
    + "REDDIT_LATEST_SUBREDIT_POST_COMMENTARY"

## Subscription:
+ id: 296633 (string, required)
+ userID: 2363692 (string, required)
+ accessToken: 26396363 (string, required)
+ ServiceType: Youtube (ServiceName, required)

## Service
+ name: Youtube (ServiceName, required)
+ widgets_name: YT_NB_FOLLOWERS, YT_NB_LIKE (array[WidgetType], required)

## WidgetConfig
+ id: (string, required)
+ subscriptionsId: 296633 (string, required)
+ type: YT_NB_FOLLOWERS (WidgetType)
+ isAuthentificated: true (boolean, required)
+ refreshRate: 3 (number, required)

## YT_NB_FOLLOWERS_CONF (WidgetConfig)
+ channel_id: PRIME (string, required)

## YT_NB_LIKE_CONF (WidgetConfig)
+ video_id: `https://www.youtube.com/watch?v=ZghJqBwIpYI` (string, required)

## OW_WEATHER_CONF (WidgetConfig)
+ country: France (string, optional)
+ city: Bayonne (string, required)

## HNNbLatestPost (WidgetConfig)
+ nb_wanted_post: 4 (number, required)

## REDDIT_LATEST_SUBREDIT_POST_NAME_CONF (WidgetConfig)
+ subreddit_name: "Rust" (string, required)
+ nb_wanted_post: 4 (number, required)

## REDDIT_LATEST_SUBREDIT_POST_COMMENTARY_CONF (WidgetConfig)
+ subreddit_name: "Rust" (string, required)
+ post_name: "When will Rust kill cpp ?" (string, required)
