# ServiceSubscribe

Subscribe Spec

## Service Collection [/services]

### Get subscriptions [GET]

+ Response 200 (application/json)
    + Header
        client_id: "356278"
    + Attributes (array)
        + (Service)
        + (Service)
            + name: Reddit
            + widgets: REDDIT_LATEST_SUBREDIT_POST_NAME, REDDIT_LATEST_SUBREDIT_POST_COMMENTARY

### Post subscriptions [Post]

+ Attributes (Service)
+ Request (application/json)
    + Attributes (Service)

# Data Structures

## ServiceName (enum[String])
    + "Youtube"
    + "Reddit"
    + "Hackernews"
    + "twitter"

## WidgetType (enum[String])
    + "YT_NB_FOLLOWERS"
    + "YT_NB_LIKE"
    + "OW_WEATHER"
    + "HN_NB_LATEST_POST"
    + "REDDIT_LATEST_SUBREDIT_POST_NAME"
    + "REDDIT_LATEST_SUBREDIT_POST_COMMENTARY"

## Service
+ name: Youtube (ServiceName, required)
+ widgets_name: YT_NB_FOLLOWERS, YT_NB_LIKE (array[WidgetType], required)

## WIDGET
+ id: (string, required)
+ is_authentificated: true (bool, required)
+ refresh_rate: (number, required)

## YT_NB_FOLLOWERS_CONF (WIDGET)
+ channel_id: PRIME (string, required)

## YT_NB_LIKE_CONF (WIDGET)
+ video_id: https://www.youtube.com/watch?v=ZghJqBwIpYI (string, required)

## OW_WEATHER_CONF (WIDGET)
+ country: France (string, optional)
+ city: Bayonne (string)

## HN_NB_LATEST_POST_CONF (WIDGET)
+ nb_wanted_post: 4 (number)

## REDDIT_LATEST_SUBREDIT_POST_NAME_CONF (WIDGET)
+ subreddit_name: "Rust" (string)
+ nb_wanted_post: 4 (number)

## REDDIT_LATEST_SUBREDIT_POST_COMMENTARY_CONF (WIDGET)
+ subreddit_name: "Rust" (string, required)
+ post_name: "When will Rust kill cpp ?"
