# Group Party

Generic party description

## Party Collection [/parties{?type}{?nbElements}{?page}]

+ Parameters
    + type: (PartyType, optional) - PUBLIC PRIVATE EVENT
    + nbElements: (number, optional)
        + Default: 10
    + page: (number, optional) - Current page
        + Default: 0

### Get paginated parties [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (Party)
        + (Party)
            + name: Chez fanfan
            + type: PUBLIC

## Party [/parties]

### Create new Party [POST]

+ Attributes (Party)
+ Request (application/json)
    + Attributes (Party)

+ Response 201

# Data Structures

## PartyType (enum[string])
    + "PRIVATE"
    + "PUBLIC"
    + "EVENT"

## Party (object)
+ id: 348868764 (string, required)
+ ownerId: 987sdfsdf (string, required)
+ type: PRIVATE (PartyType, required)
+ name: Soirass nico (string, required)
+ beginDate: 8557986 (string, optional)
+ endDate: 8557986 (string, optional)
+ location: (Location, optional)

## PublicParty (Party)

## PrivateParty (Party)

## EventParty (Party)

## Location
+ name: Bordeaux (string)
+ latitude: -23422 (string)
+ longitude: 4645 (string)
